//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntFMSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int pkod { get; set; }
        public string personelkodu { get; set; }
        public Nullable<int> kod { get; set; }
        public Nullable<int> kod1 { get; set; }
        public Nullable<int> subekodu { get; set; }
        public string departman { get; set; }
        public string gorevi { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string adresi { get; set; }
        public string aktif { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string ozel { get; set; }
        public string seri { get; set; }
        public Nullable<int> kimlikno { get; set; }
        public string babaadi { get; set; }
        public string anaadi { get; set; }
        public string dogyeri { get; set; }
        public Nullable<System.DateTime> dogtar { get; set; }
        public string medhali { get; set; }
        public string ilk { get; set; }
        public string ilcek { get; set; }
        public string mahkoy { get; set; }
        public Nullable<short> ciltno { get; set; }
        public Nullable<short> ailesirano { get; set; }
        public Nullable<short> sirano { get; set; }
        public string veryer { get; set; }
        public Nullable<System.DateTime> vertarih { get; set; }
        public string kayitno { get; set; }
        public string everil { get; set; }
        public string everilce { get; set; }
        public Nullable<int> ebelgeno { get; set; }
        public Nullable<System.DateTime> etarih { get; set; }
        public string egrup { get; set; }
        public string kangrup { get; set; }
        public string tahkodu { get; set; }
        public Nullable<int> aktfatilkno { get; set; }
        public Nullable<int> aktfatsonno { get; set; }
        public Nullable<int> eskfatilkno { get; set; }
        public Nullable<int> eskfatsonno { get; set; }
        public Nullable<int> akttesilkno { get; set; }
        public Nullable<int> akttessonno { get; set; }
        public Nullable<int> esktesilkno { get; set; }
        public Nullable<int> esktessonno { get; set; }
        public Nullable<int> tasirsilkno { get; set; }
        public Nullable<int> tasirssonno { get; set; }
        public Nullable<int> ensontesno { get; set; }
        public Nullable<int> ensonfatno { get; set; }
        public Nullable<int> ensontasno { get; set; }
        public string resmiseri { get; set; }
        public string acikseri { get; set; }
        public string resmiserifat { get; set; }
        public string makbuzseri { get; set; }
        public string tasseri { get; set; }
        public string isaret { get; set; }
        public string kasa { get; set; }
        public string FatMakSeri { get; set; }
        public Nullable<int> FatMakSonNo { get; set; }
        public Nullable<int> alisFatno { get; set; }
        public string alisFatSeri { get; set; }
        public string FirmaKodu { get; set; }
        public string FirmaAdi { get; set; }
        public Nullable<int> YeniTahsilatMakbuzilkno { get; set; }
        public Nullable<int> YeniTahsilatMakbuzsonno { get; set; }
        public Nullable<int> EskiTahsilatMakbuzilkno { get; set; }
        public Nullable<int> EskiTahsilatMakbuzsonno { get; set; }
        public string sskNo { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public string MacAdres { get; set; }
        public string IpAdres { get; set; }
        public string BilgisayarIsmi { get; set; }
        public Nullable<System.DateTime> tarih2 { get; set; }
        public string DagitimFisSeri { get; set; }
        public Nullable<int> DagitimFisNo { get; set; }
        public string GidisGrupFatura { get; set; }
        public string GelisGrupFatura { get; set; }
        public string GidisGrupMakbuz { get; set; }
        public string GelisGrupMakbuz { get; set; }
        public string fgrup { get; set; }
        public string fiskonto { get; set; }
        public string Yol { get; set; }
        public string Yemek { get; set; }
        public string Navlun { get; set; }
        public string AlinanAvans { get; set; }
        public string VerilenAvans { get; set; }
        public string VerilenHizmetGrupFatura { get; set; }
        public string SigortaGrup { get; set; }
        public string KasaKodu { get; set; }
        public string KasaAdi { get; set; }
        public string KAktif { get; set; }
        public string Durum { get; set; }
        public byte[] Resim { get; set; }
        public string EFatSeri { get; set; }
        public Nullable<int> EFatilkNo { get; set; }
        public Nullable<int> EFatSonNo { get; set; }
        public Nullable<int> EFatAktifNo { get; set; }
    }
}
