//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura
    {
        public int @ref { get; set; }
        public int TakipNo { get; set; }
        public string takipseri { get; set; }
        public string kim { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> vtarih { get; set; }
        public Nullable<System.DateTime> ciktarih { get; set; }
        public string ciksaat { get; set; }
        public string teslim { get; set; }
        public Nullable<System.DateTime> teslimtar { get; set; }
        public string teslimsaat { get; set; }
        public string teslimaciklama { get; set; }
        public string teslimadi { get; set; }
        public string teslimsoyadi { get; set; }
        public string teslimbabadi { get; set; }
        public string teslimdogyer { get; set; }
        public Nullable<System.DateTime> teslimdogtar { get; set; }
        public string teslimplaka { get; set; }
        public string teslimyeri { get; set; }
        public string teslimkimlikno { get; set; }
        public string teslimtipi { get; set; }
        public Nullable<int> belgeno { get; set; }
        public string belgeseri { get; set; }
        public string iptal { get; set; }
        public Nullable<int> iptalfaturano { get; set; }
        public Nullable<decimal> iptalfattop { get; set; }
        public Nullable<System.DateTime> iptaltarihi { get; set; }
        public string iptalacikla { get; set; }
        public string basildimi { get; set; }
        public string carikod { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string carikod1 { get; set; }
        public string adi1 { get; set; }
        public string soyadi1 { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> varissube { get; set; }
        public Nullable<int> alicisube { get; set; }
        public Nullable<int> gonderensube { get; set; }
        public string adres { get; set; }
        public string adresalim { get; set; }
        public string adresteslim { get; set; }
        public string telihihbar { get; set; }
        public string sigorta { get; set; }
        public Nullable<decimal> adresalimb { get; set; }
        public Nullable<decimal> adresteslimb { get; set; }
        public Nullable<decimal> telihihbarb { get; set; }
        public Nullable<decimal> sigortab { get; set; }
        public Nullable<decimal> yekun { get; set; }
        public Nullable<decimal> toplam { get; set; }
        public Nullable<decimal> toplamkdv { get; set; }
        public Nullable<short> iskonto { get; set; }
        public Nullable<decimal> iskontob { get; set; }
        public string iade { get; set; }
        public Nullable<System.DateTime> iadetar { get; set; }
        public string tahsil { get; set; }
        public string tahkodu { get; set; }
        public Nullable<int> tahsilsube { get; set; }
        public Nullable<System.DateTime> tahsiltar { get; set; }
        public string onay { get; set; }
        public string odemetipi { get; set; }
        public string ozelkod { get; set; }
        public string algon_hesap { get; set; }
        public Nullable<short> albolkodu { get; set; }
        public Nullable<short> gonbolkodu { get; set; }
        public Nullable<int> kdv { get; set; }
        public string tipi { get; set; }
        public Nullable<System.DateTime> belgetarihi { get; set; }
        public string kdvdahil { get; set; }
        public string vergidairesi { get; set; }
        public string vergino { get; set; }
        public string ackap { get; set; }
        public Nullable<int> vadegun { get; set; }
        public Nullable<System.DateTime> vadetar { get; set; }
        public string cahesapkod { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string isaret { get; set; }
        public string aciklama2 { get; set; }
        public Nullable<int> tahisaret { get; set; }
        public Nullable<decimal> tahsiltutar { get; set; }
        public Nullable<decimal> tahsilmiktar { get; set; }
        public Nullable<int> bodrono { get; set; }
        public Nullable<int> kasano { get; set; }
        public Nullable<int> fatisaret { get; set; }
        public Nullable<int> aktarim { get; set; }
        public Nullable<System.DateTime> zimmettarih { get; set; }
        public Nullable<int> gonisaret { get; set; }
        public Nullable<int> alisaret { get; set; }
        public Nullable<int> Sorunlumu { get; set; }
        public string Ustcarikod { get; set; }
        public string islemtipi { get; set; }
        public Nullable<int> mahsupfisno { get; set; }
        public string muhasebelesti { get; set; }
        public string muhasebeonay { get; set; }
        public string kontrolaciklama { get; set; }
        public string muhasebeDatabase { get; set; }
        public string muhasebeDonem { get; set; }
        public string Cariyebirak { get; set; }
        public Nullable<int> DekontNo { get; set; }
        public Nullable<int> kdv1 { get; set; }
        public Nullable<decimal> TevkifatKdvTutar { get; set; }
        public Nullable<decimal> BeyanEdilecekKdv { get; set; }
        public Nullable<decimal> TahsilEdilecekTutar { get; set; }
        public Nullable<int> alinanisaret { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public string tahsilet { get; set; }
        public string GrpKodu { get; set; }
        public string KesilenEkran { get; set; }
        public string DovizKodu { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public string KurTipi { get; set; }
        public Nullable<int> KarOrani { get; set; }
        public Nullable<int> BTakipNo { get; set; }
        public string BTakipSeri { get; set; }
        public Nullable<System.DateTime> DegisimTarih { get; set; }
        public Nullable<int> dTakipno { get; set; }
        public string dTakipSeri { get; set; }
        public Nullable<int> GTakipNo { get; set; }
        public string GTakipSeri { get; set; }
        public Nullable<int> imageRef { get; set; }
        public Nullable<int> Aktarma { get; set; }
        public string Modul { get; set; }
        public Nullable<short> EFatura { get; set; }
        public string EFaturaNo { get; set; }
        public Nullable<short> EFaturaTipi { get; set; }
        public Nullable<short> EFaturaDurum { get; set; }
    }
}
