//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliye
    {
        public int tasirno { get; set; }
        public string irsno { get; set; }
        public string seri { get; set; }
        public Nullable<int> seferno { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> gonsub { get; set; }
        public string gonsubadi { get; set; }
        public Nullable<int> alhat { get; set; }
        public string alhatadi { get; set; }
        public Nullable<int> alsub { get; set; }
        public string alsubadi { get; set; }
        public string plaka { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string sofadi { get; set; }
        public string sofsoyadi { get; set; }
        public Nullable<decimal> sigorta { get; set; }
        public Nullable<decimal> adresteslim { get; set; }
        public Nullable<decimal> adresalim { get; set; }
        public Nullable<decimal> telihbar { get; set; }
        public Nullable<decimal> toplam { get; set; }
        public Nullable<decimal> yekun { get; set; }
        public Nullable<decimal> kdv { get; set; }
        public string iptal { get; set; }
        public Nullable<System.DateTime> iptaltarihi { get; set; }
        public string basildimi { get; set; }
        public string kim { get; set; }
        public string muhurno { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public Nullable<decimal> Navlun { get; set; }
        public Nullable<decimal> Navlunkdv { get; set; }
        public Nullable<decimal> Navluntoplam { get; set; }
        public Nullable<decimal> alavans { get; set; }
        public Nullable<decimal> veravans { get; set; }
        public Nullable<decimal> potoplam { get; set; }
        public Nullable<decimal> uatoplam { get; set; }
        public Nullable<double> toplamkg { get; set; }
        public string isaret { get; set; }
        public Nullable<int> takipno { get; set; }
        public string takipseri { get; set; }
        public Nullable<int> sayfasay { get; set; }
        public Nullable<int> msayfasay { get; set; }
        public Nullable<decimal> gtoplam { get; set; }
        public Nullable<decimal> mgtoplam { get; set; }
        public Nullable<decimal> muatoplam { get; set; }
        public Nullable<decimal> mpotoplam { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> irsaliye1 { get; set; }
        public Nullable<int> aktarim { get; set; }
        public Nullable<int> takipnoson { get; set; }
        public Nullable<decimal> navlunacik { get; set; }
        public Nullable<int> hat { get; set; }
        public string hatismi { get; set; }
        public Nullable<decimal> sigortatutar { get; set; }
        public Nullable<decimal> merkezsigorta { get; set; }
        public Nullable<decimal> subesigorta { get; set; }
        public Nullable<decimal> odenenacik { get; set; }
        public Nullable<decimal> alinanacik { get; set; }
        public string kimbosalt { get; set; }
        public string durum { get; set; }
        public Nullable<int> gonisaret { get; set; }
        public Nullable<int> alisaret { get; set; }
        public string RomorkPlaka { get; set; }
        public Nullable<int> PuantorKod { get; set; }
        public Nullable<decimal> EkNavlun { get; set; }
        public string EkNavlunAciklama { get; set; }
        public Nullable<decimal> EkNavlunAlici { get; set; }
        public string EkNavlunAciklamaAlici { get; set; }
        public Nullable<decimal> SigortaPrimTutar { get; set; }
        public Nullable<decimal> SigortaPrimOran { get; set; }
        public string YetkiBelgeNo { get; set; }
        public Nullable<System.DateTime> tarih1 { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public Nullable<System.DateTime> saat1 { get; set; }
        public string Sigortaci { get; set; }
        public string PoliceNo { get; set; }
        public string Sisaret { get; set; }
        public Nullable<decimal> TesSigortaTutar { get; set; }
        public Nullable<int> SeferNo1 { get; set; }
        public Nullable<int> YukleyenPKod { get; set; }
        public string GidisGelis { get; set; }
        public Nullable<System.DateTime> DegisimTarih { get; set; }
        public Nullable<int> BasKM { get; set; }
        public Nullable<int> BitKM { get; set; }
        public Nullable<int> SeferRef { get; set; }
        public Nullable<double> ToplamDesi { get; set; }
        public Nullable<int> PlakaHesapId { get; set; }
        public Nullable<int> CiktiSayi { get; set; }
        public Nullable<int> AracirsListeRef { get; set; }
    }
}
