//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class krhatsub
    {
        public int @ref { get; set; }
        public Nullable<int> hat { get; set; }
        public string hatismi { get; set; }
        public int sube { get; set; }
        public string subeismi { get; set; }
        public Nullable<int> baglisube { get; set; }
        public Nullable<int> bagakt { get; set; }
        public Nullable<short> mrkuzaklik { get; set; }
        public Nullable<int> poorani { get; set; }
        public Nullable<int> uaorani { get; set; }
        public Nullable<int> chorani { get; set; }
        public string carikod { get; set; }
        public string muhkodu { get; set; }
        public string ozelkod1 { get; set; }
        public Nullable<int> okod1 { get; set; }
        public string ozelkod2 { get; set; }
        public Nullable<int> okod2 { get; set; }
        public string ozelkod3 { get; set; }
        public Nullable<int> okod3 { get; set; }
        public Nullable<short> bolgekodu { get; set; }
        public Nullable<int> aktfatilkno { get; set; }
        public Nullable<int> aktfatsonno { get; set; }
        public Nullable<int> eskfatilkno { get; set; }
        public Nullable<int> eskfatsonno { get; set; }
        public Nullable<int> akttesilkno { get; set; }
        public Nullable<int> akttessonno { get; set; }
        public Nullable<int> esktesilkno { get; set; }
        public Nullable<int> esktessonno { get; set; }
        public Nullable<int> irsilkno { get; set; }
        public Nullable<int> irssonno { get; set; }
        public string adres { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string semt { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string sifre { get; set; }
        public string postakodu { get; set; }
        public Nullable<int> subetipi { get; set; }
        public Nullable<int> gelorani { get; set; }
        public Nullable<int> gitorani { get; set; }
        public string isaret { get; set; }
        public string KKB { get; set; }
        public string KdvHesabi { get; set; }
        public string durum { get; set; }
        public string kendifaturasi { get; set; }
        public Nullable<int> KKBOran { get; set; }
        public Nullable<int> teslimSuresi { get; set; }
        public string pazartesi { get; set; }
        public string sali { get; set; }
        public string Carsamba { get; set; }
        public string Persembe { get; set; }
        public string Cuma { get; set; }
        public string Cumartesi { get; set; }
        public string pazar { get; set; }
        public string NavlunGiderKodu { get; set; }
        public string GonderenEkNavlunGiderKodu { get; set; }
        public string VerilenAvansGiderKodu { get; set; }
        public string AliciEkNavlunGiderKodu { get; set; }
        public string HizmetAlimFaturaGiderKodu { get; set; }
        public string FaturaGiderKodu { get; set; }
        public string MazotGiderKodu { get; set; }
        public string HakedisGiderKodu { get; set; }
        public string YolGiderKodu { get; set; }
        public string YemekGiderKodu { get; set; }
        public string iskontoGiderKodu { get; set; }
        public string FaturaBaglantiKodu { get; set; }
        public string AlısFaturaBaglantiKodu { get; set; }
        public string gelirMuhasebeKodu { get; set; }
        public string ModemTipi { get; set; }
        public Nullable<decimal> OnayLimit { get; set; }
        public string SQLServer { get; set; }
        public string SQLDatabase { get; set; }
        public string SQLUserName { get; set; }
        public string SQLPassword { get; set; }
        public string BSeri { get; set; }
        public Nullable<int> BSubeKodu { get; set; }
        public string BSubeismi { get; set; }
        public Nullable<int> BAliciSubeKodu { get; set; }
        public string BAliciSubeismi { get; set; }
        public Nullable<bool> AktarimYap { get; set; }
        public Nullable<bool> MKAktar { get; set; }
        public Nullable<bool> MKAktarTumu { get; set; }
        public Nullable<bool> AnlAktar { get; set; }
        public Nullable<bool> TesAktar { get; set; }
        public Nullable<bool> TesAktarTumu { get; set; }
        public Nullable<bool> IrsAktar { get; set; }
        public Nullable<bool> IrsAktarTumu { get; set; }
        public Nullable<bool> FatAktar { get; set; }
        public Nullable<bool> FatAktarTumu { get; set; }
        public Nullable<bool> KasaAktar { get; set; }
        public Nullable<bool> KasaAktarTumu { get; set; }
        public Nullable<bool> TBAktar { get; set; }
        public Nullable<bool> TBAktarTumu { get; set; }
        public Nullable<bool> BankaAktar { get; set; }
        public Nullable<bool> BankaAktarTumu { get; set; }
        public Nullable<bool> CekAktar { get; set; }
        public Nullable<bool> CekAktarTumu { get; set; }
        public Nullable<System.DateTime> AktarimTarih { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> AlisFatAktar { get; set; }
        public Nullable<bool> AlisFatAktarTumu { get; set; }
        public string LogoKurumsal { get; set; }
        public string LogoBireysel { get; set; }
        public string LogoNakliyeci { get; set; }
        public string LogoSatici { get; set; }
        public string LogoPersonel { get; set; }
        public string LogoOrtaklar { get; set; }
        public string LogoKamyoncu { get; set; }
        public string LogoKomyonetci { get; set; }
        public string LogoAcente { get; set; }
        public string LogoOzel1 { get; set; }
        public string LogoOzel2 { get; set; }
        public string LogoKamukurumu { get; set; }
        public string LogoDefMuhasebe { get; set; }
        public string FirmaCarikodu { get; set; }
        public string SubeCariKodu { get; set; }
        public Nullable<short> FaturaDuzeltSon { get; set; }
        public Nullable<short> imageAktar { get; set; }
        public Nullable<short> OKT { get; set; }
        public Nullable<int> PaletBarkod { get; set; }
        public Nullable<short> Ambar { get; set; }
        public Nullable<short> Dagitim { get; set; }
        public string HizmetKartiFatura { get; set; }
        public string LogoSEmanet { get; set; }
        public Nullable<int> MusOzelKodRef { get; set; }
        public string AliciCariKodu { get; set; }
    }
}
