//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class krmuste
    {
        public int muskod { get; set; }
        public string kodu { get; set; }
        public string kim { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> sube { get; set; }
        public string subeismi { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
        public string semt { get; set; }
        public string cadde { get; set; }
        public string mahalle { get; set; }
        public string sokak { get; set; }
        public string diger { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string adres3 { get; set; }
        public string adres4 { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string tel3 { get; set; }
        public string tel4 { get; set; }
        public string tel5 { get; set; }
        public string tel6 { get; set; }
        public string email { get; set; }
        public string poskod { get; set; }
        public string aciklama { get; set; }
        public string vdairesi { get; set; }
        public string vno { get; set; }
        public string iskolu { get; set; }
        public string ozelkod1 { get; set; }
        public string ozelkod2 { get; set; }
        public string ozelkod3 { get; set; }
        public string carikod { get; set; }
        public string muhkodu { get; set; }
        public string caritipi { get; set; }
        public string eskikod { get; set; }
        public string sifre { get; set; }
        public Nullable<int> skodu { get; set; }
        public string belgetipi { get; set; }
        public string serino { get; set; }
        public string kimlikno { get; set; }
        public string pasportno { get; set; }
        public string ehliyetno { get; set; }
        public string mtipi { get; set; }
        public string tkodu { get; set; }
        public string tadi { get; set; }
        public string tahkodu { get; set; }
        public string isaret { get; set; }
        public string krliste { get; set; }
        public string kodu1 { get; set; }
        public Nullable<int> aktarim { get; set; }
        public string kdvda { get; set; }
        public Nullable<int> makbuz { get; set; }
        public Nullable<float> sigorta { get; set; }
        public string topluFatura { get; set; }
        public string DizaynDosya { get; set; }
        public string uretici { get; set; }
        public string DosMusteriKodu { get; set; }
        public string GetirenKodu { get; set; }
        public string GetirenAdi { get; set; }
        public string GetirenTipi { get; set; }
        public Nullable<decimal> GetirenTutar { get; set; }
        public Nullable<decimal> GetirenOran { get; set; }
        public Nullable<decimal> Tahakkuktutar { get; set; }
        public string TahakkukGun { get; set; }
        public string TahakkukAck { get; set; }
        public string TahakkukGrp { get; set; }
        public Nullable<decimal> TahakkukBirimUcret { get; set; }
        public Nullable<decimal> Tahakkukikramiye { get; set; }
        public Nullable<short> TahakkukKacGunde { get; set; }
        public string CariHareketGiris { get; set; }
        public string GoturenKodu { get; set; }
        public string GoturenAdi { get; set; }
        public string GoturenTipi { get; set; }
        public Nullable<decimal> GoturenTutar { get; set; }
        public Nullable<decimal> GoturenOran { get; set; }
        public string KaraListeAciklama { get; set; }
        public string Ekleyen { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<decimal> Alacak { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<decimal> BorcG { get; set; }
        public Nullable<decimal> AlacakG { get; set; }
        public Nullable<decimal> BakiyeG { get; set; }
        public Nullable<short> VadeGun { get; set; }
        public Nullable<int> IskoluId { get; set; }
        public Nullable<int> SanalSubeKodu { get; set; }
        public string FirmaKodu { get; set; }
        public string DepoKodu { get; set; }
        public Nullable<bool> KendiDeposu { get; set; }
        public Nullable<int> TahsilatGunu { get; set; }
        public string HizmetAlimGiris { get; set; }
        public string sec { get; set; }
        public Nullable<bool> BarkodBas { get; set; }
        public Nullable<System.DateTime> DegisimTarih { get; set; }
        public Nullable<int> GuzergahKodu { get; set; }
        public string PTahKodu { get; set; }
        public string PTipi { get; set; }
        public Nullable<decimal> PTutar { get; set; }
        public Nullable<int> POranPay { get; set; }
        public Nullable<int> POranPayda { get; set; }
        public string CariSifre { get; set; }
        public string UstCari { get; set; }
        public string UstCariKodu { get; set; }
        public string UstCariAdi { get; set; }
        public string Spot { get; set; }
        public Nullable<short> MusirsnoGiris { get; set; }
        public string MOdemeTipi { get; set; }
        public Nullable<short> EkDosya { get; set; }
        public Nullable<short> EFatura { get; set; }
        public Nullable<short> EFaturaTipi { get; set; }
        public Nullable<int> NakliyeSekli { get; set; }
    }
}
