//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tesellum
    {
        public int @ref { get; set; }
        public int TakipNo { get; set; }
        public string takipseri { get; set; }
        public Nullable<int> FatNo { get; set; }
        public string kim { get; set; }
        public Nullable<System.DateTime> vtarih { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> ciktarih { get; set; }
        public string ciksaat { get; set; }
        public string teslim { get; set; }
        public Nullable<System.DateTime> teslimtar { get; set; }
        public string teslimsaat { get; set; }
        public string teslimaciklama { get; set; }
        public string teslimadi { get; set; }
        public string teslimsoyadi { get; set; }
        public string teslimbabadi { get; set; }
        public string teslimdogyer { get; set; }
        public Nullable<System.DateTime> teslimdogtar { get; set; }
        public string teslimplaka { get; set; }
        public string teslimyeri { get; set; }
        public string teslimkimlikno { get; set; }
        public string teslimtipi { get; set; }
        public Nullable<int> belgeno { get; set; }
        public string belgeseri { get; set; }
        public string iptal { get; set; }
        public Nullable<int> iptalfaturano { get; set; }
        public Nullable<decimal> iptalfattop { get; set; }
        public Nullable<System.DateTime> iptaltarihi { get; set; }
        public string iptalacikla { get; set; }
        public string basildimi { get; set; }
        public string carikod { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string carikod1 { get; set; }
        public string adi1 { get; set; }
        public string soyadi1 { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> varissube { get; set; }
        public Nullable<int> alicisube { get; set; }
        public Nullable<int> gonderensube { get; set; }
        public string adres { get; set; }
        public string adresalim { get; set; }
        public string adresteslim { get; set; }
        public string telihihbar { get; set; }
        public string sigorta { get; set; }
        public Nullable<decimal> adresalimb { get; set; }
        public Nullable<decimal> adresteslimb { get; set; }
        public Nullable<decimal> telihihbarb { get; set; }
        public Nullable<decimal> sigortab { get; set; }
        public Nullable<decimal> yekun { get; set; }
        public Nullable<decimal> toplam { get; set; }
        public Nullable<decimal> toplamkdv { get; set; }
        public Nullable<short> iskonto { get; set; }
        public Nullable<decimal> iskontob { get; set; }
        public string iade { get; set; }
        public Nullable<System.DateTime> iadetar { get; set; }
        public string tahsil { get; set; }
        public Nullable<int> tahsilsube { get; set; }
        public Nullable<System.DateTime> tahsiltar { get; set; }
        public string onay { get; set; }
        public string odemetipi { get; set; }
        public string ozelkod { get; set; }
        public string algon_hesap { get; set; }
        public Nullable<short> albolkodu { get; set; }
        public Nullable<short> gonbolkodu { get; set; }
        public Nullable<int> kdv { get; set; }
        public string isaret { get; set; }
        public string tkodu { get; set; }
        public string tadi { get; set; }
        public string peronno { get; set; }
        public string tasirsno { get; set; }
        public Nullable<int> fatisaret { get; set; }
        public string Turu { get; set; }
        public Nullable<int> Emanetno { get; set; }
        public string gtel1 { get; set; }
        public string gtel2 { get; set; }
        public string atel1 { get; set; }
        public string atel2 { get; set; }
        public string tti { get; set; }
        public string basisaret { get; set; }
        public string ilkkim { get; set; }
        public Nullable<int> hizliyavas { get; set; }
        public Nullable<int> aktarim { get; set; }
        public string fatseri { get; set; }
        public string kdvda { get; set; }
        public Nullable<int> cevirme { get; set; }
        public Nullable<int> gonisaret { get; set; }
        public Nullable<int> alisaret { get; set; }
        public string aciklama1 { get; set; }
        public string silisaret { get; set; }
        public Nullable<int> Puantorkod { get; set; }
        public Nullable<int> EvrakDurum { get; set; }
        public string MalGetirenKod { get; set; }
        public string MalGetirenadi { get; set; }
        public string MalalanKod { get; set; }
        public string Malalanadi { get; set; }
        public Nullable<int> MalGetFatNo { get; set; }
        public string MalGetseri { get; set; }
        public Nullable<int> MalAlFatNo { get; set; }
        public string MalAlseri { get; set; }
        public string iptaliadeKodu { get; set; }
        public Nullable<int> Cevrimisaret { get; set; }
        public string gvno { get; set; }
        public string avno { get; set; }
        public string tvno { get; set; }
        public Nullable<int> ZimmetNo { get; set; }
        public Nullable<int> PostaBasi { get; set; }
        public string Zimmetsaat { get; set; }
        public Nullable<System.DateTime> zimmetTarih { get; set; }
        public Nullable<int> ServisSayisi { get; set; }
        public string TasiyiciKodu { get; set; }
        public string Tasiyici { get; set; }
        public Nullable<int> GonSanalSube { get; set; }
        public Nullable<int> ToplamaZimmetNo { get; set; }
        public string plaka { get; set; }
        public string GUZERGAHKODU { get; set; }
        public string etf { get; set; }
        public Nullable<decimal> Kesinti { get; set; }
        public string btesseri { get; set; }
        public Nullable<int> btesno { get; set; }
        public string GGDegisiklik { get; set; }
        public Nullable<System.DateTime> DegisimTarih { get; set; }
        public string GetTipi { get; set; }
        public Nullable<decimal> GetTutar { get; set; }
        public Nullable<int> GetPay { get; set; }
        public Nullable<int> GetPayda { get; set; }
        public string GotTipi { get; set; }
        public Nullable<decimal> GotTutar { get; set; }
        public Nullable<int> GotPay { get; set; }
        public Nullable<int> GotPayda { get; set; }
        public string BarkodNo { get; set; }
        public Nullable<System.DateTime> BarkodTarih { get; set; }
        public string BarkodSaat { get; set; }
        public Nullable<System.Guid> EmanetID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> imageRef { get; set; }
        public Nullable<int> GonMusSube { get; set; }
        public Nullable<int> AlMusSube { get; set; }
        public Nullable<int> imageRef2 { get; set; }
        public string Enlem { get; set; }
        public string Boylam { get; set; }
        public Nullable<decimal> DereceTutar { get; set; }
        public Nullable<decimal> DereceToplam { get; set; }
        public string DagitimKodu { get; set; }
        public Nullable<short> EkDosya { get; set; }
        public Nullable<int> NakliyeSekli { get; set; }
    }
}
