//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFaturaApp.EntFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tesellumhar
    {
        public int @ref { get; set; }
        public Nullable<int> fatno { get; set; }
        public string cinsi { get; set; }
        public Nullable<float> miktar { get; set; }
        public string birimi { get; set; }
        public string olcu { get; set; }
        public Nullable<double> agirlik { get; set; }
        public Nullable<int> en { get; set; }
        public Nullable<int> boy { get; set; }
        public Nullable<int> yukseklik { get; set; }
        public Nullable<double> desi_kg { get; set; }
        public Nullable<decimal> fiyati { get; set; }
        public Nullable<decimal> tutari { get; set; }
        public string takipseri { get; set; }
        public string carpan { get; set; }
        public string musirsno { get; set; }
        public string tasirsno { get; set; }
        public Nullable<decimal> emanet { get; set; }
        public Nullable<decimal> iskonto { get; set; }
        public Nullable<decimal> Fiyati1 { get; set; }
        public Nullable<decimal> tutari1 { get; set; }
        public string CarpanDesi { get; set; }
        public string AktarimRef { get; set; }
        public Nullable<float> SanalMiktar { get; set; }
        public Nullable<float> miktar1 { get; set; }
        public string birimi1 { get; set; }
        public Nullable<int> Derece { get; set; }
        public Nullable<decimal> DereceFiyat { get; set; }
        public Nullable<decimal> DereceTutar { get; set; }
        public Nullable<int> LineNr { get; set; }
        public Nullable<int> AracirsListeSira { get; set; }
    }
}
